name: xSpawn
main: dev.drygo.XSpawn.XSpawn
version: 1.0.11b
api-version: 1.20
authors:
  - Drygo
soft-depend:
  - xTeams
description: "Set custom spawnpoints per player, per xTeams team, or global. Useful for Events!"
website: https://modrinth.com/plugin/xspawn
commands:
  xspawn:
    aliases:
      - xsp
      - xs
    description: "xSpawn plugin command."
permissions:
  xspawn.admin:
    default: false
    children:
      xspawn.set:
        default: false
      xspawn.tp:
        default: false
      xspawn.del:
        default: false
      xspawn.reload:
        default: false
      xspawn.help:
        default: false
      xspawn.info:
        default: false